### ISSUE TITLE
Use encrypted channels

### ISSUE THREAD

**Issue by 1440000bytes** [uncle-jj/JoinStr#1]
Implement encrypted channels in joinstr

Details: https://gitlab.com/-/snippets/3620499

Related NIPs: 38, 48 and 112

**Comment by VividhPandey003** [comment]
Hey could you please tell me the tech stack required for this?

**Comment by 1440000bytes** [comment]
@VividhPandey003 Python and Nostr

See https://pypi.org/project/nostr-protocol/

**Comment by VividhPandey003** [comment]
Hmm, I haven't worked with it. @1440000bytes Would you recommend me to learn it and work on it or should I leave it for somebody else to work on. I'd love your advice on this.
